pipeline {
    
    agent any 
    
    stages {
        
        stage('Checkout'){
           steps {
                //git credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', 
                url: 'https://github.com/RajashekarDandamudi/Jenkins-Zero-To-Hero.git',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t python-jenkins-argocd-k8s .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push rajashekardandamudi/python-jenkins-argocd-k8s

                    '''
                }
            }
        }
    }
}
